from __future__ import annotations

from collections import defaultdict
from datetime import datetime
from pathlib import Path

from lab_radar.config import LabRadarConfig
from lab_radar.items import RadarItem


def write_daily_report(
    items: list[RadarItem],
    config: LabRadarConfig,
    report_date: str,
    out_dir: str | Path = "reports",
) -> Path:
    Path(out_dir).mkdir(parents=True, exist_ok=True)
    path = Path(out_dir) / f"{report_date}.md"
    visible = _visible_items(items, config)
    by_source: dict[str, list[RadarItem]] = defaultdict(list)
    for item in visible:
        by_source[item.source].append(item)

    lines: list[str] = [
        f"# 今日科研雷达 {report_date}",
        "",
        "## 总览",
        "",
        f"- 候选条目：{len(items)}",
        f"- 报告展示：{len(visible)}",
        f"- Core：{sum(1 for item in items if item.category == 'core')}",
        f"- Adjacent：{sum(1 for item in items if item.category == 'adjacent')}",
        f"- Wildcard：{sum(1 for item in items if item.category == 'wildcard')}",
        "",
        "## 今日行动建议",
        "",
    ]
    top_actions = sorted(visible, key=lambda item: item.action_score, reverse=True)[:5]
    if top_actions:
        for index, item in enumerate(top_actions, start=1):
            lines.append(f"{index}. **{item.title}**：{item.action_suggestion}")
    else:
        lines.append("今天没有发现高相关条目。可以放过自己，继续深度工作。")
    lines.append("")

    _append_section(lines, "必看论文", by_source.get("arxiv", []), config.report_value("daily_top_papers", 5))
    _append_section(lines, "值得关注的开源项目", by_source.get("github", []), config.report_value("daily_top_repos", 5))
    _append_section(lines, "值得关注的模型/资源", by_source.get("huggingface", []), config.report_value("daily_top_models", 5))

    lines.extend(
        [
            "## 趋势信号",
            "",
            *_trend_lines(visible),
            "",
            "---",
            "",
            f"Generated by Lab Radar at {datetime.now().isoformat(timespec='seconds')}.",
        ]
    )
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def _visible_items(items: list[RadarItem], config: LabRadarConfig) -> list[RadarItem]:
    include_noise = bool(config.report_value("include_noise", False))
    filtered = [item for item in items if include_noise or item.category != "noise"]
    return sorted(filtered, key=lambda item: item.action_score, reverse=True)


def _append_section(lines: list[str], title: str, items: list[RadarItem], limit: int) -> None:
    lines.extend([f"## {title}", ""])
    selected = sorted(items, key=lambda item: item.action_score, reverse=True)[: int(limit)]
    if not selected:
        lines.extend(["暂无高相关条目。", ""])
        return
    for item in selected:
        lines.extend(
            [
                f"### [{item.title}]({item.url})",
                "",
                f"- 分类：{item.category}",
                f"- 评分：相关 {item.relevance_score} / 新颖 {item.novelty_score} / 影响 {item.impact_score} / 行动 {item.action_score}",
                f"- 作者/所有者：{item.authors_or_owner or '未知'}",
                f"- 摘要：{item.summary}",
                f"- 相关原因：{item.reason}",
                f"- 建议：{item.action_suggestion}",
                "",
            ]
        )


def _trend_lines(items: list[RadarItem]) -> list[str]:
    keyword_counts: dict[str, int] = defaultdict(int)
    for item in items:
        text = f"{item.title} {item.abstract_or_description}".lower()
        for token in ["robot", "embodied", "diffusion", "world model", "humanoid", "sim2real", "vla", "ros2"]:
            if token in text:
                keyword_counts[token] += 1
    if not keyword_counts:
        return ["- 暂无明显趋势信号。"]
    return [f"- `{key}` 出现 {value} 次" for key, value in sorted(keyword_counts.items(), key=lambda pair: pair[1], reverse=True)]
